name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 5.4
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Build package
        run: pnpm build
      - name: Run test
        run: npm test
