name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install Deps
        run: pnpm install --frozen-lockfile
      - name: Build package
        run: pnpm build
      - name: Run test
        run: npm test
